### ISSUE TITLE
How to run this ? ./halftone seems not possible

### ISSUE THREAD

**Issue by vindarel** [Shinmera/halftone#1]
Hello,
by the lack of instructions I tried a `chmod +x halftone` (deep in Contents/Application) but it throws a `error format for exec(): halftone`. 

I'm on Debian and I may not have all Qt libs installed.

Thanks !

**Comment by Shinmera** [comment]
You downloaded the OS X release. Try [this one](https://github.com/Shinmera/halftone/releases/tag/1.0.1) or simply:

```
(ql:quickload :halftone)
(halftone:start)
```

**Comment by vindarel** [comment]
I'd never have found myself^^ (it was the second time I tried…) thanks. Works like a charm. Gonna have to study this source code.
